[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "surplus-funds-aggregator"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.31",
    "beautifulsoup4>=4.12",
    "pdfplumber>=0.10",
    "openpyxl>=3.1",
    "sqlalchemy>=2.0",
    "psycopg[binary]>=3.2", # PostgreSQL driverm=
    "alembic>=1.13",
    "python-dotenv>=1.0", # reads key-value pairs vrom .env file and loads them as env variables

]

[project.optional-dependencies]
dev = [
    "pytest>=8",
    "pytest-cov>=5",   # code coverage with tests
    "ruff>=0.6",       # PEP 8, lint, formatting
    "pip-audit>=2.7",  # known vulnerabilities
]


[project.scripts]
surplus-funds = "surplus_funds.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.ruff]
line-length = 120
target-version = "py310"
src = ["src", "tests"]

[tool.ruff.lint]
# E/W = PEP 8, F = pyflakes, I = import order,
# B = usual bugs, UP = modern sintax, S = security
select = ["E", "W", "F", "I", "B", "UP", "S"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]
