"""Create sources and surplus_funds tables

Revision ID: c8a5fb1a11f1
Revises:
Create Date: 2026-09-30 18:59:11.172032

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c8a5fb1a11f1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("county", sa.String(length=100), nullable=False),
        sa.Column("agency", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("file_format", sa.String(length=10), nullable=False),
        sa.Column("list_updated_at", sa.Date(), nullable=True),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "surplus_funds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("parcel_id", sa.String(length=100), nullable=True),
        sa.Column("case_number", sa.String(length=100), nullable=True),
        sa.Column("owner_name", sa.String(length=255), nullable=True),
        sa.Column("buyer_name", sa.String(length=255), nullable=True),
        sa.Column("property_address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("sale_date", sa.Date(), nullable=True),
        sa.Column("sale_date_precision", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    op.create_index(op.f("ix_surplus_funds_owner_name"), "surplus_funds", ["owner_name"], unique=False)
    op.create_index(op.f("ix_surplus_funds_parcel_id"), "surplus_funds", ["parcel_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_surplus_funds_parcel_id"), table_name="surplus_funds")
    op.drop_index(op.f("ix_surplus_funds_owner_name"), table_name="surplus_funds")
    op.drop_table("surplus_funds")
    op.drop_table("sources")
    # ### end Alembic commands ###
